### PR TITLE
Testing functional tests in python3

### PR DESCRIPTION
**Pull request by phobologic**

### CODE REVIEW

**Comment by xiaket** [comment]
For the record, the full traceback looks like this:

```
[2018-06-27T11:46:15] Using default AWS provider mode
[2018-06-27T11:46:19] 49
Traceback (most recent call last):
  File "/Users/shi.kaix/sandbox/2/stacker/plan.py", line 93, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/Users/shi.kaix/sandbox/2/stacker/actions/build.py", line 314, in _launch_stack
    stack_policy=stack_policy)
  File "/Users/shi.kaix/sandbox/2/stacker/providers/aws/default.py", line 672, in create_stack
    self.cloudformation.create_stack(**args)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/endpoint.py", line 148, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/endpoint.py", line 173, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/endpoint.py", line 157, in create_request
    operation_name=operation_model.name)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/signers.py", line 156, in sign
    auth.add_auth(request)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/auth.py", line 358, in add_auth
    canonical_request = self.canonical_request(request)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/auth.py", line 305, in canonical_request
    body_checksum = self.payload(request)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/auth.py", line 267, in payload
    if request.body and hasattr(request.body, 'seek'):
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/awsrequest.py", line 378, in body
    p.prepare_body(self.data, self.files)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/vendored/requests/models.py", line 456, in prepare_body
    body = self._encode_params(data)
  File "/Users/shi.kaix/sandbox/venv2/lib/python2.7/site-packages/botocore/vendored/requests/models.py", line 97, in _encode_params
    return urlencode(result, doseq=True)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1348, in urlencode
    v = quote_plus(v)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1305, in quote_plus
    return quote(s, safe)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1298, in quote
    return ''.join(map(quoter, s))
KeyError: 49
[2018-06-27T11:46:19] vpc: failed (49)
[2018-06-27T11:46:19] The following steps failed: vpc
```

I think this is a result of a defect in the library `future` that we've used to bridge the gap between Python 2 and Python 3.

In `stacker/actions/build.py`, we have used `str` to force all the parameters into a string so it could be accepted by Cloudformation. On seeing the use of `str`, `future` tries to replace that with a class defined in `future.types.newstr`, so it behaves more or less like unicode(thus bridging the gap).

The issue is the `newstr` instance is later transformed into a `newbytes` instance, and it cannot be quoted because of a flaw in `future`. The following snippet will reproduce the error above:

```
#!/usr/bin/env python
from builtins import bytes         # This comes from `future`
from urllib import quote

quote(bytes('10.128.0.0/16'), safe='')
```

FYI, that 49 comes from the ascii repr of '1'.

There are several ways to fix this issue:

1. report this flaw to `future` and ask them to fix this from upstream.

This should be our best approach, however, I think the development of `future` is somehow stagnant, so it could take a very long time.

2. Avoid the use of `newstr`/`newbytes`.

It is not possible to avoid it altogether, but I do think we could avoid the use of `newstr`/`newbytes` in this specific case, since we are not really looking for that unicode behaviour.

I'll push a commit to my branch and fix this.

**Comment by xiaket** [comment]
After 05c179, I still got a few errors locally, but I guess most of them are related to the role setup. The only concern I have is:

```
 ✗ stacker build - no parallelism
   (from function `assert_has_line' in file ./test_helper.bash, line 39,
    in test file ./suite.bats, line 919)
     `assert_has_line "vpc1: submitted (creating new stack)"' failed
   $ stacker build -j 1 /dev/fd/63
   [2018-06-27T13:06:37] Using default AWS provider mode
   [2018-06-27T13:06:41] vpc1: skipped (nochange)
   [2018-06-27T13:06:44] vpc2: submitted (creating new stack)
   [2018-06-27T13:06:50] vpc2: complete (creating new stack)

   $ stacker destroy --force /dev/fd/63
   [2018-06-27T13:06:51] Using default AWS provider mode
   [2018-06-27T13:06:53] vpc1: submitted (submitted for destruction)
   [2018-06-27T13:06:53] vpc2: submitted (submitted for destruction)
   [2018-06-27T13:06:56] vpc2: complete (stack destroyed)
   [2018-06-27T13:06:56] vpc1: complete (stack destroyed)
```

I'll look into it soon.

**Comment by xiaket** [comment]
All tests passed locally now(with the exception of profiles, which is expected).

**Comment by phobologic** [comment]
@xiaket went ahead and merged your most recent changes in your branch, letting the tests run now.  Thanks!

**Pull request closed without merging**
