### PR TITLE
Let raw templates use previous Parameter values

### LINKED ISSUE #593: Raw templates do not use existing parameters
When diffing/building with a raw template, existing parameters/variables do not get used.

```[2018-05-07T08:33:30] ERROR my-app stacker.plan:91(_run_once): Variable "MyParameter" in blueprint "my-app" is missing
Traceback (most recent call last):
  File "/home/aaron.gorka/.local/lib/python2.7/site-packages/stacker/plan.py", line 89, in _run_once
    status = self.fn(self.stack, status=self.status)
  File "/home/aaron.gorka/.local/lib/python2.7/site-packages/stacker/actions/diff.py", line 228, in _diff_stack
    stack.resolve(self.context, provider)
  File "/home/aaron.gorka/.local/lib/python2.7/site-packages/stacker/stack.py", line 187, in resolve
    self.blueprint.resolve_variables(self.variables)
  File "/home/aaron.gorka/.local/lib/python2.7/site-packages/stacker/blueprints/raw.py", line 139, in resolve_variables
    self.name
  File "/home/aaron.gorka/.local/lib/python2.7/site-packages/stacker/blueprints/raw.py", line 63, in resolve_variable
    raise MissingVariable(blueprint_name, var_name)
MissingVariable: Variable "MyParameter" in blueprint "my-app" is missing
[2018-05-07T08:33:30] DEBUG my-app stacker.plan:143(set_status): Setting my-app state to failed.
[2018-05-07T08:33:30] INFO my-app stacker.ui:37(info): my-app: failed (Variable "MyParameter" in blueprint "my-app" is missing)
[2018-05-07T08:33:30] ERROR MainThread stacker.actions.base:188(execute): The following steps failed: my-app
```

In this case the `my-app` stack is already deployed with the parameter `MyParameter` as `NoEcho`. Ideally, It would be nice if Stacker could understand that the parameter is already set and can be reused with the `UsePreviousValue` setting when building (http://boto3.readthedocs.io/en/latest/reference/services/cloudformation.html#CloudFormation.Client.create_stack). When running a diff, it can assume that nothing has changed.

Stacker version: 1.3.0
Steps to reproduce: manually deploy a CloudFormation template with 1 parameter (ideally `NoEcho` as there seems to be some logic in `_handle_missing_parameters` that _pulls_ the existing values down). Then, run a diff/build with the variable omitted.

### PR DESCRIPTION
**Pull request by phobologic**
This changes a couple of things:

1. We now use the `UsePreviousValue` argument for parameters that exist in an existing stack, rather than getting the value there and providing it ourselves.  This is more "cloudformation-y".
2. The raw blueprint no longer handles missing variables on it's own - it didn't need to, because `stacker.actions.build._handle_missing_parameters` already handles this for us.

Fixes #593

### CODE REVIEW

**Comment by phobologic** [comment]
BTW, if anyone has a better idea than using a class to represent when we should `UsePreviousValue` I'm all ears.  This was the cleanest way I could think to make this change without having to change existing tests.

**Comment by phobologic** [comment]
@troyready would love your eyes on this as well, as it changes the way the raw blueprints work.

**Comment by troyready** [comment]
I really, really like the simplicity of it.

**Comment by phobologic** [comment]
This has a small potential bug in it, though it's more a question of what people would expect the behavior to be.  As it's written now, if a stack has a `Default` parameter and you do not pass anything in for it, then on update, it will use that Default - rather than `UsePreviousValue`.  This means that if the template ever changes it's Default, that is what will be used, causing an update.

I think the right order of resolution for Parameters should be:

- If a parameter is passed in via the config, use that.
- If there is an existing stack and it has the Parameter already, `UsePreviousValue`
- If there is a `Default` on the Parameter, use that value.

Does that sound right to everyone? @troyready @ejholmes @aarongorka ?

**Comment by phobologic** [comment]
Ok, I have a test suite now that fails in master, but is fixed here.

## in master:
```
# TESTS=28 make -C tests test
./stacker.yaml.sh | stacker build -
[2018-07-07T13:14:15] Using default AWS provider mode
[2018-07-07T13:14:17] stackerFunctionalTests: skipped (nochange)
bats  test_suite/28_*
 ✗ stacker build - raw template parameter resolution
   (from function `assert_has_line' in file test_suite/../test_helper.bash, line 39,
    in test file test_suite/28_stacker_build-raw_template_parameter_resolution.bats, line 68)
     `assert_has_line "vpc: skipped (nochange)"' failed
   PWD: /Users/mike/git/cloudtools/stacker/tests
   $ stacker build /dev/fd/63
   [2018-07-07T13:14:20] Using default AWS provider mode
   [2018-07-07T13:14:22] vpc: submitted (creating new stack)
   [2018-07-07T13:14:27] vpc: complete (creating new stack)

   $ stacker build /dev/fd/63
   [2018-07-07T13:14:28] Using default AWS provider mode
   [2018-07-07T13:14:29] vpc: submitted (updating existing stack)
   [2018-07-07T13:14:33] vpc: complete (updating existing stack)

   $ stacker destroy --force /dev/fd/63
   [2018-07-07T13:14:34] Using default AWS provider mode
   [2018-07-07T13:14:35] vpc: submitted (submitted for destruction)
   [2018-07-07T13:14:38] vpc: complete (stack destroyed)


1 test, 1 failure
make: *** [test] Error 1
```

## in this branch:
```
# TESTS=28 make -C tests test
./stacker.yaml.sh | stacker build -
[2018-07-07T13:13:21] Using default AWS provider mode
[2018-07-07T13:13:23] stackerFunctionalTests: skipped (nochange)
bats  test_suite/28_*
 ✓ stacker build - raw template parameter resolution

1 test, 0 failures
```

This makes this PR rely on #597 since I got sick of having to run all the tests :)

**Pull request merged**
